name: Tests Windows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  msvc:
    uses: ./.github/workflows/test_base.yml
    with:
      platform_name: Windows MSVC
      runner: windows-latest
      configure_preset: native-release
      compiler_family: msvc

  mingw:
    uses: ./.github/workflows/test_base.yml
    with:
      platform_name: Windows MinGW
      runner: windows-latest
      configure_preset: mingw-release
      compiler_family: mingw
