name: Tests Linux

on:
  push:
    branches: [main]
  pull_request:

jobs:
  gcc:
    uses: ./.github/workflows/test_base.yml
    with:
      platform_name: Linux GCC
      runner: ubuntu-latest
      configure_preset: native-release
      compiler_family: gcc

  clang:
    uses: ./.github/workflows/test_base.yml
    with:
      platform_name: Linux Clang
      runner: ubuntu-latest
      configure_preset: clang-release
      compiler_family: clang
